### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by Qcat0214** [Slivo-fr/TranqRotate#1]
Libs dep missing so it can't be loaded separately..add it pls :)

**Comment by Slivo-fr** [comment]
Thanks for checkiing this out ! 

You're right, in fact I was planning to release a zip file containing those once I tested it during next MC raid.
I also need to work on the .pkgmeta file that will contain references to libs.

I don't like the idea of adding external libs files to this repository itself

**Comment by Qcat0214** [comment]
oh cool. ill look forward to the next release.also i would like to ask u to update the zhCN & zhTW localization in the next push. Thank you. Cheers! :)

zhCN:

    ["LOADED_MESSAGE"] = "TranqRotate 已加载, 输入 /tranq 进入设置",

    -- Settings
    --- Announces
    ["SETTING_ANNOUNCES"] = "通告",
    ["ENABLE_ANNOUNCES"] = "启用通告",
    ["ENABLE_ANNOUNCES_DESC"] = "启用 / 禁用通告",

    ---- Channels
    ["ANNOUNCES_CHANNEL_HEADER"] = "通告频道",
    ["MESSAGE_CHANNEL_TYPE"] = "发送到",
    ["MESSAGE_CHANNEL_TYPE_DESC"] = "你想发送到哪个频道",
    ["MESSAGE_CHANNEL_NAME"] = "频道名或玩家名",
    ["MESSAGE_CHANNEL_NAME_DESC"] = "自定义设置要发送消息的玩家或频道的名称",

    ----- Channels types

    ["CHANNEL_WHISPER"] = "私聊",
    ["CHANNEL_CHANNEL"] = "频道",
    ["CHANNEL_RAID_WARNING"] = "团队警报",
    ["CHANNEL_SAY"] = "说",
    ["CHANNEL_YELL"] = "大喊",
    ["CHANNEL_PARTY"] = "队伍",
    ["CHANNEL_RAID"] = "团队",

    ---- Messages
    ["ANNOUNCES_MESSAGE_HEADER"] = "通告信息",
    ["SUCCESS_MESSAGE_LABEL"] = "施放成功通告信息",
    ["FAIL_MESSAGE_LABEL"] = "施放失败通告信息",

    ['DEFAULT_SUCCESS_ANNOUNCE_MESSAGE'] = "已对 %s 施放了宁神射击!",
    ['DEFAULT_FAIL_ANNOUNCE_MESSAGE'] = "!!! 对 %s 宁神失败!!!",

    --- Profiles
    ["SETTING_PROFILES"] = "配置"

------------------------------------------------------------------

zhTW:

    ["LOADED_MESSAGE"] = "TranqRotate 已加載, 輸入 /tranq 進入設置",

    -- Settings
    --- Announces
    ["SETTING_ANNOUNCES"] = "通告",
    ["ENABLE_ANNOUNCES"] = "啟用通告",
    ["ENABLE_ANNOUNCES_DESC"] = "啟用 / 禁用通告",

    ---- Channels
    ["ANNOUNCES_CHANNEL_HEADER"] = "通告頻道",
    ["MESSAGE_CHANNEL_TYPE"] = "發送到",
    ["MESSAGE_CHANNEL_TYPE_DESC"] = "你想發送到哪個頻道",
    ["MESSAGE_CHANNEL_NAME"] = "頻道名或玩家名",
    ["MESSAGE_CHANNEL_NAME_DESC"] = "自定義設置要發送消息的玩家或頻道的名稱",

    ----- Channels types

    ["CHANNEL_WHISPER"] = "私聊",
    ["CHANNEL_CHANNEL"] = "頻道",
    ["CHANNEL_RAID_WARNING"] = "團隊警報",
    ["CHANNEL_SAY"] = "說",
    ["CHANNEL_YELL"] = "大喊",
    ["CHANNEL_PARTY"] = "隊伍",
    ["CHANNEL_RAID"] = "團隊",

    ---- Messages
    ["ANNOUNCES_MESSAGE_HEADER"] = "通告資訊",
    ["SUCCESS_MESSAGE_LABEL"] = "施放成功通告資訊",
    ["FAIL_MESSAGE_LABEL"] = "施放失敗通告資訊",

    ['DEFAULT_SUCCESS_ANNOUNCE_MESSAGE'] = "已對 %s 施放了寧神射擊!",
    ['DEFAULT_FAIL_ANNOUNCE_MESSAGE'] = "!!! 對 %s 寧神失敗!!!",

    --- Profiles
    ["SETTING_PROFILES"] = "配置"

**Comment by Slivo-fr** [comment]
Sure ! Thanks for your contribution :)

**Comment by Slivo-fr** [comment]
Done in 2f90eacb222e08f898f0fc92e20129284221bf33

**Comment by Slivo-fr** [comment]
Hey @Qcat0214, I just released a first beta. Your feedback would be appreciated :D

**Comment by Qcat0214** [comment]
Still show errors..
I think you are missing the libs include in the .toc file




Message: Interface\AddOns\TranqRotate\TranqRotate.lua:4: attempt to call global 'LibStub' (a nil value)
Time: Tue Dec 10 18:12:17 2019
Count: 1
Stack: Interface\AddOns\TranqRotate\TranqRotate.lua:4: attempt to call global 'LibStub' (a nil value)
Interface\AddOns\TranqRotate\TranqRotate.lua:4: in main chunk

**Comment by Slivo-fr** [comment]
It's probably loaded by another addon on my side, I'll check this tonight on a character with no other addons and fix it. Thanks for your help :D

**Comment by Qcat0214** [comment]
In addition, I found that 2 libs were missing from your first release **"AceGUI-3.0 and CallbackHandler-1.0"**

and I've edited .toc file and it's working well atm. following:


Libs\LibStub\LibStub.lua
Libs\CallbackHandler-1.0\CallbackHandler-1.0.xml
Libs\AceDB-3.0\AceDB-3.0.xml
Libs\AceDBOptions-3.0\AceDBOptions-3.0.xml
Libs\AceGUI-3.0\AceGUI-3.0.xml
Libs\AceConfig-3.0\AceConfig-3.0.xml

**Comment by Slivo-fr** [comment]
Should be fixed with the new release, thanks for your help :)
